variables:
  CCACHE_COMPILERCHECK: content
  CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

build-gcc7:
  stage: build
  image: ubuntu:18.04
  tags: [docker]
  before_script:
    - apt-get update && apt-get -y install --no-install-recommends g++ ninja-build qt{base,declarative,tools,multimedia,script,quickcontrols2-}5-dev qml-module-qt{gstreamer,multimedia,quick-extras,-labs-settings,graphicaleffects,quick-controls2} libqt5svg5-dev liblmdb-dev libgl1-mesa-dev libssl-dev git ccache
    # need recommended deps for wget
    - apt-get -y install wget
    - wget https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.sh && sh cmake-3.15.5-Linux-x86_64.sh  --skip-license  --prefix=/usr/local
    - /usr/sbin/update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:${PATH}"
    - mkdir -p build
    - cmake -GNinja -H. -Bbuild
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_INSTALL_PREFIX=.deps/usr
        -DHUNTER_ROOT=".hunter"
        -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHUNTER_CONFIGURATION_TYPES=RelWithDebInfo
        -DUSE_BUNDLED_OPENSSL=OFF
        -DCI_BUILD=ON
    - cmake --build build
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .hunter/
      - .ccache

build-flatpak-amd64:
  stage: build
  image: ubuntu:latest
  tags: [docker]
  before_script:
    - apt-get -y install --no-install-recommends flatpak-builder git
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak --noninteractive install --user flathub org.kde.Platform//5.14
    - flatpak --noninteractive install --user flathub org.kde.Sdk//5.14
  script:
    - export VERSION=$(git describe)
    - mkdir -p build-flatpak
    - cd build-flatpak
    - flatpak-builder --ccache --repo=repo --subject="Build of Nheko ${VERSION} `date`" app ../io.github.NhekoReborn.Nheko.json
    - flatpak build-bundle repo nheko-${VERSION}-amd64.flatpak io.github.NhekoReborn.Nheko ${CI_COMMIT_REF_NAME}
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build-flatpak/.flatpak-builder
  artifacts:
    expose_as: 'flatpak-amd64'
    paths: ['nheko-${VERSION}-amd64.flatpak']
    name: flatpak-${CI_COMMIT_REF_NAME}-amd64

