build-gcc7:
  stage: build
  image: ubuntu:18.04
  tags: [docker]
  before_script:
    - apt update && apt -y curl install g++ ninja-build qtbase5-dev qt5base qt5tools qt5svg qt5multimedia qt5quickcontrols2 qt5graphicaleffects liblmdb-dev libgl1-mesa-dev
    - curl https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.sh | bash -s  --skip-license  --prefix=/usr/local
  script:
    - cmake --version
    - cmake -GNinja -H. -Bbuild \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_INSTALL_PREFIX=.deps/usr \
      -DHUNTER_ROOT=".hunter" \
      -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHUNTER_CONFIGURATION_TYPES=RelWithDebInfo \
      -DUSE_BUNDLED_OPENSSL=OFF \
      -DCI_BUILD=ON
    - cmake --build
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .hunter/


