variables:
  CCACHE_COMPILERCHECK: content
  CCACHE_DIR: .ccache

build-gcc7:
  stage: build
  image: ubuntu:18.04
  tags: [docker]
  before_script:
    - apt update && apt -y install --no-install-recommends g++ ninja-build qt{base,declarative,tools,multimedia,script,quickcontrols2-}5-dev qml-module-qt{gstreamer,multimedia,quick-extras,-labs-settings,graphicaleffects,quick-controls2} libqt5svg5-dev liblmdb-dev libgl1-mesa-dev libssl-dev git ccache
    # need recommended deps for wget
    - apt -y install wget
    - wget https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.sh && sh cmake-3.15.5-Linux-x86_64.sh  --skip-license  --prefix=/usr/local
  script:
    - mkdir -p build
    - cmake -GNinja -H. -Bbuild
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_INSTALL_PREFIX=.deps/usr
        -DHUNTER_ROOT=".hunter"
        -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHUNTER_CONFIGURATION_TYPES=RelWithDebInfo
        -DUSE_BUNDLED_OPENSSL=OFF
        -DCI_BUILD=ON
    - cmake --build build
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .hunter/
      - .ccache


